# Generated by Django 4.1.3 on 2023-05-08 10:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMAGeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amicale_jeune', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Amicale Jeune')),
                ('amicale_adulte', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Amicale Adulte')),
                ('our_story', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Notre Histoire')),
            ],
        ),
        migrations.CreateModel(
            name='SMAParoisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom de la paroisse')),
                ('desc', models.CharField(max_length=100, verbose_name='Petite description')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Page de la paroisse')),
            ],
        ),
        migrations.CreateModel(
            name='SOMAGG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bureau', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Le Bureau SOMAGG')),
                ('somagg', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Détails sur SOMAGG')),
                ('gallery', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Gallerie SOMAGG')),
            ],
        ),
    ]
