# Generated by Django 4.1.3 on 2023-05-08 10:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMAProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Responsables projets SMA')),
                ('details', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Projets de la province')),
                ('gallery', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Gallerie Photos des projets')),
            ],
        ),
    ]
