# Generated by Django 4.1.3 on 2023-05-10 08:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_smaproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMANews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('desc', models.CharField(max_length=250)),
                ('details', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Contenu de l'actualité")),
            ],
        ),
    ]
